### ISSUE TITLE
add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by jacobandresen** [DBCDK/biblo#1]
it is currently hard to do 'drive-by' hacks on this project. It is hard to get running for a random hacker passing by. Looks like it runs on private packages ?  A contributers guide could be good.

 Here are some quick questions 

- What to do if you don't have a @dbcdk/dbc-config ? Can you still help? 
- Do you accept outside pull requests?

Maybe you could supply a default test/dummy dbc-config file.

This CONTRIBUTING guide looks good: https://github.com/kbhff/eggplant/blob/master/CONTRIBUTING.rst

**Comment by hrmoller** [comment]
Thanks for your input, @jacobandresen 

We're aware that we're missing both some contribution guidelines as well as some example config stuff. 
It's not as easy as it might sound because some of the webservices the application is using are locked down behind our firewall and as no one before you has issued a wish of using our stuff we've hardly payed this area any attention.
But we've heard your call and we'll see what we can do to get your going.

BTW: We've just created this repo today and first task is to peel of the frontend as this is a completely new project. It is based on the codebase found here: https://github.com/DBCDK/mobilsoeg which probably will enter a bit more quiet period for the next month or so.

**Comment by rasmuserik** [comment]
+1

I had the same issue with missing `@dbcdk/dbc-config` 
when trying to build mobilsoeg a while ago,
and did not get any further at that time.

Another questions for `CONTRIBUTING.md` is:
whether there is another public issue-tracker,
or if we can just use github issues as usual?

**Comment by hyatt03** [comment]
The github issues tracker is the only public bug tracker for this project,
feel free to use it :)
Den 19/01/2016 06.28 skrev "RasmusErik Voel Jensen" <
notifications@github.com>:

**Comment by hrmoller** [comment]
The issue is on the backlog and hopefully it will be prioritised soon.

**Comment by jacobandresen** [comment]
contribution guidelines are covered in README.md . 

dependency on dbcdk config module is handled here: https://github.com/DBCDK/serviceprovider/issues/21
